# -*- coding: utf-8 -*-
"""Daily PM-monitoring / health corpus for 2026-07-27 (PubMed entry window 2026/07/24-27)."""

# subtopic keys
MECH = "Mechanistic toxicology"
CVM  = "Cardiovascular & metabolic"
NEU  = "Neuro / mental health"
RESP = "Respiratory & allergic"
REPR = "Reproductive & developmental"
EXPO = "Exposure assessment & modelling"
SENS = "Sensing, forecasting & instrumentation"
OCC  = "Occupational & indoor"
BURD = "Burden, policy & mitigation"
OTHR = "Other clinical endpoints"

PAPERS = [
 dict(pmid="42496976", short="Dales 2026",
      title="Wildfire-sourced PM2.5 and ED visits for migraine and other primary headache",
      journal="JAMA Netw Open", doi="10.1001/jamanetworkopen.2026.25015",
      sub=NEU, design="Case-crossover", pm="PM2.5 (wildfire)", geo="Canada",
      endpoint="Neurological", n="997,701 ED visits", tier="A"),
 dict(pmid="42500877", short="Yang 2026",
      title="Short-term PM2.5 and hospitalisation/ED use in atrial fibrillation (Medicare, western US)",
      journal="J Am Heart Assoc", doi="10.1161/JAHA.125.046917",
      sub=CVM, design="Case-crossover", pm="PM2.5 (wildfire-influenced)", geo="USA",
      endpoint="Cardiovascular", n="26,158 patients", tier="A"),
 dict(pmid="42497094", short="Glover 2026",
      title="Umbrella meta-review of urban environmental exposures and cognitive health",
      journal="Age Ageing", doi="10.1093/ageing/afag215",
      sub=NEU, design="Umbrella review / meta-analysis", pm="PM2.5", geo="Global",
      endpoint="Cognitive", n="54 SRs / 270 associations", tier="A"),
 dict(pmid="42502136", short="Xi 2026",
      title="Air pollution, built environment and temperature vs. prediabetes phenotypes (KORA)",
      journal="Diabetologia", doi="10.1007/s00125-026-06814-2",
      sub=CVM, design="Prospective cohort", pm="PM2.5", geo="Germany",
      endpoint="Metabolic", n="1,618 participants", tier="A"),
 dict(pmid="42492753", short="Xie 2026",
      title="Long-term PM2.5 and timing of pubertal development in boys and girls",
      journal="Environ Res", doi="10.1016/j.envres.2026.125313",
      sub=REPR, design="Prospective cohort", pm="PM2.5", geo="China",
      endpoint="Endocrine / puberty", n="3,833 children", tier="B"),
 dict(pmid="42503559", short="Peterson 2026",
      title="Ambient air pollution, PAHs and pubertal development: critical review",
      journal="Curr Environ Health Rep", doi="10.1007/s40572-026-00552-8",
      sub=REPR, design="Critical review", pm="PM2.5 components", geo="Global",
      endpoint="Endocrine / puberty", n="-", tier="B"),
 dict(pmid="42508106", short="Huang 2026",
      title="Joint prenatal bisphenol + air-pollutant mixture exposure and preschool IQ",
      journal="Ecotoxicol Environ Saf", doi="10.1016/j.ecoenv.2026.120566",
      sub=REPR, design="Prospective cohort (mixtures)", pm="PM2.5 / PM10", geo="China",
      endpoint="Neurodevelopment", n="231 mother-child pairs", tier="B"),
 dict(pmid="42498385", short="Chen 2026",
      title="Prenatal air pollution, fetal growth trajectory phenotypes and child neurodevelopment",
      journal="J Environ Sci (China)", doi="10.1016/j.jes.2025.10.043",
      sub=REPR, design="Prospective cohort", pm="PM2.5 / PM10", geo="China",
      endpoint="Neurodevelopment", n="Birth cohort", tier="B"),
 dict(pmid="42494991", short="Goossens 2026",
      title="In utero air pollution exposure and pre-/postnatal brain development (imaging review)",
      journal="Neurosci Appl", doi="10.1016/j.nsa.2026.107019",
      sub=NEU, design="Narrative review", pm="PM2.5 / PM10 / PMcoarse", geo="Global",
      endpoint="Neurodevelopment", n="-", tier="B"),
 dict(pmid="42503941", short="Pan 2026",
      title="Maternal PM exposure and offspring neurodevelopment: effects and mechanisms",
      journal="Zhonghua Yu Fang Yi Xue Za Zhi", doi="10.3760/cma.j.cn112150-20250804-00752",
      sub=NEU, design="Narrative review", pm="PM (bulk)", geo="China",
      endpoint="Neurodevelopment", n="-", tier="C"),
 dict(pmid="42502400", short="Ma 2026",
      title="PM2.5-induced neurotoxicity and depression: exposure risks and mechanisms",
      journal="iScience", doi="10.1016/j.isci.2026.116617",
      sub=NEU, design="Narrative review", pm="PM2.5 + components", geo="Global",
      endpoint="Mental health", n="-", tier="B"),
 dict(pmid="42496546", short="Sanchez de Prada 2026",
      title="Ambient PM and asthma-coded admissions in children 0-3 y, Spain",
      journal="Epidemiologia", doi="10.3390/epidemiologia7040097",
      sub=RESP, design="Ecological panel", pm="PM2.5 / PM10", geo="Spain",
      endpoint="Respiratory", n="20,746 municipality-years", tier="C"),
 dict(pmid="42493772", short="Liao 2026",
      title="Short-term air pollution, respiratory symptoms and lung function in asthma",
      journal="Med Gas Res", doi="10.4103/mgr.MEDGASRES-D-25-00164",
      sub=RESP, design="Panel study", pm="PM2.5 / PM10", geo="China",
      endpoint="Respiratory", n="32 patients / 266 visits", tier="C"),
 dict(pmid="42497725", short="Yang 2026b",
      title="Allergenic vs. toxic risk of airborne seed hairs compared with ambient PM2.5",
      journal="J Hazard Mater", doi="10.1016/j.jhazmat.2026.143076",
      sub=RESP, design="Field measurement", pm="PM2.5 + bioaerosol", geo="China",
      endpoint="Allergy", n="Urban+suburban campaign", tier="B"),
 dict(pmid="42496778", short="Bayar Muluk 2026",
      title="Climate change and otolaryngology: airway disease impacts and emission reduction",
      journal="Int J Biometeorol", doi="10.1007/s00484-026-03289-z",
      sub=RESP, design="Narrative review", pm="PM2.5", geo="Global",
      endpoint="Respiratory", n="-", tier="C"),
 dict(pmid="42498414", short="Ding 2026",
      title="PM2.5 promotes vascular calcification via miR-27b-5p/HES1 signalling",
      journal="J Environ Sci (China)", doi="10.1016/j.jes.2025.12.074",
      sub=MECH, design="In vitro + organoid + murine", pm="PM2.5", geo="China",
      endpoint="Cardiovascular", n="-", tier="B"),
 dict(pmid="42498412", short="Wu 2026",
      title="Macrophage NLRP3 inflammasome in real-ambient PM-induced hepatic glucose dysregulation",
      journal="J Environ Sci (China)", doi="10.1016/j.jes.2025.11.018",
      sub=MECH, design="Real-ambient murine + co-culture", pm="Real-ambient PM", geo="China",
      endpoint="Metabolic", n="-", tier="B"),
 dict(pmid="42507118", short="Maraschi 2026",
      title="Osmoregulatory disruption and metal bioaccumulation from settleable atmospheric PM (fish)",
      journal="J Comp Physiol B", doi="10.1007/s00360-026-01698-5",
      sub=MECH, design="Controlled exposure (ecotox)", pm="Settleable APM", geo="Brazil",
      endpoint="Non-human / ecotox", n="-", tier="C"),
 dict(pmid="42503956", short="Huang 2026b",
      title="PM2.5 and dyslipidaemia in rural Chinese children; dietary effect modification",
      journal="Zhonghua Liu Xing Bing Xue Za Zhi", doi="10.3760/cma.j.cn112338-20251120-00843",
      sub=CVM, design="Cross-sectional (multistage)", pm="PM2.5", geo="China",
      endpoint="Metabolic", n="10,788 children", tier="C"),
 dict(pmid="42508048", short="Kazmierska 2026",
      title="Air pollution and cardiovascular disease: review of current data",
      journal="Przegl Epidemiol", doi="10.32394/pe/218966",
      sub=CVM, design="Narrative review", pm="PM2.5 / PM10", geo="Global",
      endpoint="Cardiovascular", n="-", tier="C"),
 dict(pmid="42504215", short="Karamzad 2026",
      title="Ischaemic heart disease burden in MENA 1990-2021; PM attributable fraction 28.2%",
      journal="Health Sci Rep", doi="10.1002/hsr2.72886",
      sub=BURD, design="GBD secondary analysis", pm="Ambient PM", geo="MENA",
      endpoint="Cardiovascular", n="21 countries", tier="B"),
 dict(pmid="42498351", short="Shan 2026",
      title="Policy-driven emission reductions and post-pandemic rebound, high-resolution inventories",
      journal="J Environ Sci (China)", doi="10.1016/j.jes.2026.01.009",
      sub=BURD, design="Emission inventory", pm="PM emissions", geo="China",
      endpoint="Source / policy", n="2018/2020/2023", tier="B"),
 dict(pmid="42507642", short="Rees 2026",
      title="HEPA filtration to reduce respiratory infection in care homes (AFRI-c process evaluation)",
      journal="PLoS One", doi="10.1371/journal.pone.0347989",
      sub=BURD, design="RCT process evaluation", pm="Filtered PM", geo="UK",
      endpoint="Respiratory infection", n="22 care homes", tier="B"),
 dict(pmid="42501626", short="Shi 2026",
      title="Adaptive spatiotemporal graph transformer for multi-site multi-step PM2.5 forecasting",
      journal="J Environ Manage", doi="10.1016/j.jenvman.2026.130515",
      sub=SENS, design="Deep-learning model", pm="PM2.5", geo="China / India",
      endpoint="Not applicable", n="Multi-site networks", tier="B"),
 dict(pmid="42505456", short="Tsuchiya 2026",
      title="Seasonal and indoor-outdoor characteristics of fluorescent aerosol particles in offices",
      journal="Biosensors", doi="10.3390/bios16070380",
      sub=SENS, design="Real-time sensor campaign", pm="Bioaerosol / coarse", geo="Japan",
      endpoint="Not applicable", n="10 offices, 4 regions", tier="C"),
 dict(pmid="42494965", short="Solorzano-Araque 2026",
      title="Multiscale exposure modelling: LOTOS-EUROS + mobility surveys + particle toxicity",
      journal="GeoHealth", doi="10.1029/2025GH001621",
      sub=EXPO, design="CTM + mobility integration", pm="PM2.5 / PM10", geo="Colombia",
      endpoint="Not applicable", n="180,000 trips", tier="B"),
 dict(pmid="42497451", short="Sun 2026",
      title="Environmental exposure and area deprivation vs. paediatric hydrocephalus outcomes",
      journal="J Neurosurg Pediatr", doi="10.3171/2026.3.PEDS2615",
      sub=OTHR, design="Registry cohort + geospatial", pm="PM2.5 (satellite-derived)", geo="USA",
      endpoint="Surgical / mortality", n="881 patients", tier="B"),
 dict(pmid="42502461", short="Park 2026",
      title="Long-term PM exposure and risk of androgenetic alopecia (nationwide cohort)",
      journal="JAAD Int", doi="10.1016/j.jdin.2026.06.008",
      sub=OTHR, design="Nationwide cohort", pm="PM2.5 / PM10", geo="South Korea",
      endpoint="Dermatological", n="Nationwide", tier="C"),
 dict(pmid="42505748", short="Lupita 2026",
      title="PM2.5, preventive-care capacity and caries/edentulism burden across the EU",
      journal="Dent J", doi="10.3390/dj14070440",
      sub=OTHR, design="Ecological panel", pm="PM2.5", geo="EU-27",
      endpoint="Oral health", n="27 countries, 2020-23", tier="C"),
 dict(pmid="42503420", short="Cole 2026",
      title="Determinants of respirable crystalline silica exposure in Australian tunnelling",
      journal="Ann Work Expo Health", doi="10.1093/annweh/wxag055",
      sub=OCC, design="Observational exposure study", pm="Respirable dust / RCS", geo="Australia",
      endpoint="Occupational", n="3,288 measurements", tier="A"),
 dict(pmid="42508083", short="Ding 2026b",
      title="Stage-resolved hair Zn-isotope dynamics as a firefighting combustion-exposure tracer",
      journal="J Hazard Mater", doi="10.1016/j.jhazmat.2026.143081",
      sub=OCC, design="Repeated-measures biomarker", pm="Combustion-derived PM", geo="China",
      endpoint="Occupational", n="15 firefighters / 53 samples", tier="B"),
 dict(pmid="42496307", short="Ramsden 2026",
      title="Xenobiotic hazards in aircraft cabin air (ultrafine particles + organophosphates)",
      journal="J Xenobiot", doi="10.3390/jox16040119",
      sub=OCC, design="Review + risk economics", pm="Ultrafine particles", geo="Global",
      endpoint="Occupational", n="-", tier="C"),
 dict(pmid="42499649", short="Chen 2026b",
      title="Nested suction instrument to cut intraoperative surgical-smoke PM2.5",
      journal="Front Med Technol", doi="10.3389/fmedt.2026.1796828",
      sub=OCC, design="Bench / device experiment", pm="PM2.5 (surgical smoke)", geo="China",
      endpoint="Occupational", n="-", tier="C"),
]

# Quantitative effect estimates reported today (heterogeneous exposure contrasts - see caption)
EFFECTS = [
 dict(label="Paediatric hydrocephalus, all-cause mortality",
      exposure="High vs low PM2.5", est=3.16, lo=1.11, hi=8.99, metric="HR", src="Sun 2026"),
 dict(label="Asthma admissions, children 0-3 y",
      exposure="per IQR PM10", est=1.89, lo=1.59, hi=2.26, metric="IRR", src="Sanchez 2026"),
 dict(label="Prediabetes phenotype IFG+IGT",
      exposure="per IQR PM2.5", est=1.89, lo=1.07, hi=3.31, metric="HR", src="Xi 2026"),
 dict(label="Asthma admissions, children 0-3 y",
      exposure="per IQR PM2.5", est=1.54, lo=1.28, hi=1.85, metric="IRR", src="Sanchez 2026"),
 dict(label="Dyslipidaemia, rural children 8-15 y",
      exposure="High vs low PM2.5", est=1.501, lo=1.028, hi=2.192, metric="OR", src="Huang 2026b"),
 dict(label="AF-related ED visit",
      exposure="PM2.5 >=9 ug/m3", est=1.34, lo=1.06, hi=1.70, metric="OR", src="Yang 2026"),
 dict(label="AF-related hospitalisation",
      exposure="PM2.5 >=9 ug/m3", est=1.24, lo=1.03, hi=1.48, metric="OR", src="Yang 2026"),
 dict(label="CVD hospitalisation in AF",
      exposure="PM2.5 >=9 ug/m3", est=1.10, lo=1.01, hi=1.20, metric="OR", src="Yang 2026"),
 dict(label="Earlier testicular development (boys)",
      exposure="per 1 ug/m3 PM2.5", est=1.065, lo=1.056, hi=1.073, metric="HR", src="Xie 2026"),
 dict(label="Earlier breast development (girls)",
      exposure="per 1 ug/m3 PM2.5", est=1.044, lo=1.039, hi=1.050, metric="HR", src="Xie 2026"),
 dict(label="Earlier menarche",
      exposure="per 1 ug/m3 PM2.5", est=1.033, lo=1.025, hi=1.040, metric="HR", src="Xie 2026"),
 dict(label="Migraine/headache ED visit",
      exposure="wildfire PM2.5 (7-d lag)", est=1.0607, lo=1.0575, hi=1.0639, metric="RR-equiv", src="Dales 2026"),
]
