# -*- coding: utf-8 -*-
import os, json
os.environ["PMRW_DATE"] = "2026-08-11"
import corpus
S = corpus.SENS; E = corpus.EXPO; R = corpus.RESP; N = corpus.NEU
M = corpus.MECH; C = corpus.CVM; O = corpus.OCC; B = corpus.BURD
T = corpus.OTHR; D = corpus.REPR
MD = "Metadata only (no abstract)"

P = [
 # ---------------- Sensing, forecasting & instrumentation
 dict(pmid="42575415", short="Balasubramanian et al. 2026", doi="10.1016/j.envpol.2026.128935",
      title="Calibration model for PurpleAir-monitored PM2.5 across the United States",
      journal="Environ Pollut", sub=S, design="Calibration model comparison",
      pm="PM1, PM2.5, PM10", geo="United States", endpoint="None (instrument)",
      n="2019-2021 train / 2022 test, EPA buffers 0.5-5 km", tier="A"),
 dict(pmid="", short="Albashir 2026 (preprint)", doi="10.21203/rs.3.rs-10034990/v1",
      title="A physics-informed digital twin framework for health vigilance and indoor air quality decision support",
      journal="Res Sq (preprint)", sub=S, design="Simulation (system-level)",
      pm="Indoor PM and IAQ composite", geo="Not stated", endpoint="None (instrument)",
      n="Simulation, not peer reviewed", tier="C"),
 dict(pmid="", short="Atmos Environ 2026a", doi="10.1016/j.atmosenv.2026.122297",
      title="Reliability-constrained identification of primary and elevated aerosol structures from a single tilted Mie lidar under dust-influenced conditions",
      journal="Atmos Environ", sub=S, design=MD,
      pm="Backscatter / aerosol layer structure", geo="Not stated", endpoint="None (instrument)",
      n="Metadata only", tier="B"),
 dict(pmid="", short="Atmos Environ 2026b", doi="10.1016/j.atmosenv.2026.122296",
      title="Stable carbon isotopic composition of PM1 emissions from biomass and coal combustion under monitored combustion conditions",
      journal="Atmos Environ", sub=S, design=MD,
      pm="PM1, stable carbon isotopes", geo="Not stated", endpoint="None (instrument)",
      n="Metadata only", tier="B"),
 dict(pmid="", short="Aerosol Air Qual Res 2026", doi="10.1007/s44408-026-00157-8",
      title="Identifying winter PM2.5 sources in an urban environment using receptor modeling and nonparametric trajectory analysis",
      journal="Aerosol Air Qual Res", sub=S, design=MD,
      pm="PM2.5, source-resolved", geo="Not stated", endpoint="None (instrument)",
      n="Metadata only", tier="B"),
 # ---------------- Exposure assessment & modelling
 dict(pmid="42579110", short="Chen et al. 2026", doi="10.1021/acs.est.6c00449",
      title="Inventory uncertainty and transboundary transport of biomass-burning black carbon in southern China from radiocarbon plus modelling",
      journal="Environ Sci Technol", sub=E, design="CTM simulation + source attribution",
      pm="Black carbon, 14C source-resolved", geo="China", endpoint="None (exposure)",
      n="3 sites, year-round; NMB -68% to +28%", tier="A"),
 dict(pmid="", short="Environ Sci Atmos 2026a", doi="10.1039/d6ea00071a",
      title="Multi-scale variability and lagged meteorological controls of PM2.5 in Delhi from wavelet coherence and causality analysis",
      journal="Environ Sci Atmos", sub=E, design="Monitoring-record analysis",
      pm="PM2.5", geo="India", endpoint="None (exposure)",
      n="Abstract truncated at source", tier="B"),
 dict(pmid="", short="Atmos Pollut Res 2026", doi="10.1016/j.apr.2026.103169",
      title="High-resolution CFD modelling of traffic-related air pollutant dispersion in an urban area of Istanbul",
      journal="Atmos Pollut Res", sub=E, design=MD,
      pm="Traffic-related PM and NOx", geo="Turkiye", endpoint="None (exposure)",
      n="Metadata only", tier="B"),
 dict(pmid="", short="Atmos Environ 2026c", doi="10.1016/j.atmosenv.2026.122299",
      title="Source-specific black carbon responses to short-term interventions and cross-year emission changes in coastal Qingdao",
      journal="Atmos Environ", sub=E, design=MD,
      pm="Black carbon, source-resolved", geo="China", endpoint="None (exposure)",
      n="Metadata only", tier="B"),
 dict(pmid="", short="Deng et al. 2026", doi="10.5194/acp-26-11171-2026",
      title="Impact of black carbon on daytime valley and slope winds in idealised WRF-Chem simulations",
      journal="Atmos Chem Phys", sub=E, design="Theory / simulation",
      pm="Black carbon, radiative absorption", geo="Idealised terrain", endpoint="None (exposure)",
      n="2 simulations (BC vs no-BC)", tier="B"),
 dict(pmid="42579118", short="Herkert et al. 2026", doi="10.1021/acs.est.6c02003",
      title="Contribution of indoor air and dust to children's PFAS exposure in the Faroe Islands",
      journal="Environ Sci Technol", sub=O, design="Field measurement",
      pm="Indoor air and settled dust, PFAS", geo="Faroe Islands", endpoint="None (exposure)",
      n="40 homes; EDI for 15-year-olds", tier="B"),
 dict(pmid="42579204", short="Iavazzo et al. 2026", doi="10.1007/s10653-026-03407-1",
      title="Particle characterization in an urban synthetic turf: insights into turf and vehicular wear",
      journal="Environ Geochem Health", sub=O, design="Field measurement",
      pm="Fine, submicron and nano-sized particles; Fe, Si, Al, Br, Ni, Ag, Rh", geo="Italy",
      endpoint="None (exposure)", n="1 field; XRF, SEM-EDS, DLS; PM2.5 10.93 ug/m3 24-h", tier="A"),
 dict(pmid="42579096", short="Li et al. 2026a", doi="10.1021/acs.est.6c00994",
      title="Upgrading diesel vehicle after-treatment technology significantly changed the composition of reactive nitrogen in exhaust",
      journal="Environ Sci Technol", sub=E, design="Vehicle emission experiment",
      pm="Reactive nitrogen speciation (NO, NO2, NH3, N2O)", geo="China",
      endpoint="None (emission)", n="Light-duty diesel, China IV/V/VI", tier="B"),
 dict(pmid="", short="Atmos Environ 2026d", doi="10.1016/j.atmosenv.2026.122301",
      title="Drivers of air pollutant and greenhouse gas emissions since 2010 in the Greater Bay Area, China",
      journal="Atmos Environ", sub=B, design=MD,
      pm="PM and co-emitted pollutants, emissions", geo="China", endpoint="None (emission)",
      n="Metadata only", tier="C"),
 dict(pmid="42579113", short="Lin et al. 2026", doi="10.1021/acs.est.5c17960",
      title="Three-millennia alpine-lake records of divergent atmospheric Cd, Pb, Sb and Hg pollution in southwestern China",
      journal="Environ Sci Technol", sub=E, design="Environmental surveillance campaign",
      pm="Atmospheric metal deposition: Cd, Pb, Sb, Hg", geo="China",
      endpoint="None (exposure)", n="3 alpine lakes ~4000 m, 3000-year cores", tier="B"),
 # ---------------- Respiratory & allergic
 dict(pmid="42579806", short="Govindaraju et al. 2026", doi="10.1097/JOM.0000000000003856",
      title="Protective role of dietary antioxidant intake on long-term effects of extreme PM2.5 exposure on respiratory health",
      journal="J Occup Environ Med", sub=R, design="Cross-sectional (cohort baseline)",
      pm="Fire-sourced PM2.5", geo="Australia", endpoint="Chronic cough, phlegm, COPD",
      n="448 adults, Hazelwood Health Study", tier="B"),
 dict(pmid="42577474", short="Wang et al. 2026a", doi="10.3389/fpubh.2026.1896806",
      title="COVID-19 social interventions were associated with amplified, not attenuated, indoor-source pollutant-respiratory associations in Xi'an",
      journal="Front Public Health", sub=R, design="Retrospective time series",
      pm="PM2.5, SO2, NO2, O3", geo="China", endpoint="Respiratory outpatient visits",
      n="2,052,777 visits over 2,192 days", tier="A"),
 dict(pmid="42578310", short="Bogunia-Kubik et al. 2026", doi="10.1111/all.70474",
      title="Influence of environmental pollution on basophil reactivity to birch pollen allergens in atopic and non-atopic subjects",
      journal="Allergy", sub=R, design="Panel study",
      pm="PM2.5, PM10 (and O3)", geo="Poland", endpoint="Basophil CD63 activation, symptom scores",
      n="50 birch-allergic + 25 controls, 2 seasons", tier="B"),
 # ---------------- Mechanistic toxicology
 dict(pmid="42575013", short="Ichinose et al. 2026", doi="10.1016/j.jhazmat.2026.143239",
      title="Time-dependent bronchus-associated lymphoid tissue formation and pulmonary inflammation induced by different particulate matter types",
      journal="J Hazard Mater", sub=M, design="Animal model",
      pm="TiO2 nanoparticles, diesel exhaust particles, Asian sand dust", geo="Japan",
      endpoint="BALT formation, IL-1a, CXCL1, neutrophils", n="Murine asthma model, time course", tier="B"),
 # ---------------- Neuro / mental health
 dict(pmid="42578303", short="Sullivan et al. 2026", doi="10.1017/S095457942610159X",
      title="Longitudinal impacts of childhood neighborhood air pollution exposure on white matter integrity and cognition",
      journal="Dev Psychopathol", sub=N, design="Prospective cohort",
      pm="PM2.5", geo="United States", endpoint="Fronto-limbic FA/MD, cognition, substance use",
      n="4,511 children, ABCD, ages 9-14", tier="A"),
 dict(pmid="42577720", short="Parkinsons Dis review 2026", doi="10.1155/padi/6914112",
      title="Air pollution and Parkinson's disease pathology: clinical evidence and molecular mechanisms",
      journal="Parkinsons Dis", sub=N, design="Mechanistic review",
      pm="PM, NOx, O3", geo="Global", endpoint="Parkinson's disease incidence and progression",
      n="Narrative review", tier="C"),
 # ---------------- Other clinical endpoints
 dict(pmid="42575014", short="Wang et al. 2026b", doi="10.1016/j.jhazmat.2026.143231",
      title="Ambient PM2.5 and thyroid health: a cross-sectional study of 24,333 participants in Zhejiang, China",
      journal="J Hazard Mater", sub=T, design="Cross-sectional (multistage)",
      pm="PM2.5", geo="China", endpoint="FT4, TSH, subclinical hypothyroidism, autoimmune thyroiditis",
      n="24,333 participants, 2022-2025", tier="A"),
 dict(pmid="42579055", short="Curr Hematol Malig Rep 2026", doi="10.1007/s11899-026-00785-2",
      title="Linking air pollution and hematologic malignancies: from epidemiology to molecular mechanisms",
      journal="Curr Hematol Malig Rep", sub=T, design="Mechanistic review",
      pm="PM, benzene, NO2, SO2, arsenic, ethylene oxide", geo="Global",
      endpoint="Leukaemia, lymphoma, MDS, CHIP, myeloma", n="Narrative review", tier="C"),
 # ---------------- Burden, policy & mitigation
 dict(pmid="42576722", short="Lee et al. 2026", doi="10.3346/jkms.2026.41.e294",
      title="Toward a unified framework for climate and health research: gaps in exposure metrics and health outcomes",
      journal="J Korean Med Sci", sub=B, design="Mapping review",
      pm="Climate exposure metrics incl. air pollution", geo="Global",
      endpoint="Mortality, CVD, communicable disease and others", n="611 studies, 2000-2024", tier="B"),
 dict(pmid="42576088", short="Okeke et al. 2026", doi="10.1007/s10661-026-15800-5",
      title="Agricultural methane emissions and non-communicable disease mortality in West Africa, 2015-2020",
      journal="Environ Monit Assess", sub=B, design="Ecological panel, fixed effects",
      pm="Agricultural CH4 (Mt CO2e)", geo="West Africa", endpoint="NCD probability of death ages 30-70",
      n="11 countries, 6 years", tier="C"),
 # ---------------- Occupational & indoor
 dict(pmid="42579671", short="Alqahtani et al. 2026", doi="10.1371/journal.pone.0355166",
      title="Biomarker-based assessment of tobacco smoke exposure in Saudi females via urinary cotinine",
      journal="PLoS One", sub=O, design="Repeated-measures biomarker",
      pm="Tobacco smoke (urinary cotinine)", geo="Saudi Arabia",
      endpoint="Active and second-hand smoke exposure classification", n="133 women", tier="C"),
]

EFF = [
 dict(label="Subclinical hypothyroidism, PM2.5", exposure="per 10 ug/m3", est=1.27, lo=1.06, hi=1.51,
      metric="OR", src="Wang 2026b (J Hazard Mater)"),
 dict(label="Free thyroxine (FT4), PM2.5", exposure="per 10 ug/m3", est=0.9643, lo=0.9561, hi=0.9725,
      metric="GMR", src="Wang 2026b (J Hazard Mater)"),
 dict(label="Thyroid-stimulating hormone (TSH), PM2.5", exposure="per 10 ug/m3", est=1.1215, lo=1.0792, hi=1.1656,
      metric="GMR", src="Wang 2026b (J Hazard Mater)"),
 dict(label="Respiratory outpatient visits, SO2 (lag 4)", exposure="full period, per IQR", est=1.0911, lo=1.0386, hi=1.1464,
      metric="RR-equiv", src="Wang 2026a (Front Public Health)"),
 dict(label="Respiratory outpatient visits, SO2, strict control", exposure="2020-2022, per IQR", est=1.1840, lo=1.1029, hi=1.2711,
      metric="RR-equiv", src="Wang 2026a (Front Public Health)"),
 dict(label="Respiratory outpatient visits, SO2, post-pandemic", exposure="2023-2025, per IQR", est=1.0291, lo=0.9518, hi=1.1128,
      metric="RR-equiv", src="Wang 2026a (Front Public Health)"),
 dict(label="Respiratory outpatient visits, NO2 (lag 5)", exposure="full period, per IQR", est=1.0272, lo=1.0205, hi=1.0340,
      metric="RR-equiv", src="Wang 2026a (Front Public Health)"),
]
LC = [
 {"n": 0, "note": "no record\nthis issue"},
 {"n": 1, "note": "ABCD baseline\nwhite matter, age 9-11"},
 {"n": 3, "note": "ABCD follow-up to 14,\nthyroid FT4 under-18s,\nindoor PFAS at 15"},
 {"n": 5, "note": "Hazelwood fire cohort,\nXi'an outpatients,\nbirch-pollen panel,\ncotinine, turf players"},
 {"n": 1, "note": "Parkinson's disease\nmechanistic review"},
]
corpus.save("2026-08-11", P, EFF, "2026-08-11 -> 2026-08-11", lifecourse=LC)
print("saved", len(P), "papers,", len(EFF), "effects")
